README.adoc, aks/README.adoc, eks/README.adoc, kind/README.adoc, locals.tf
**Summary**
Loki Ingester in-memory chunks are flushed on shutdown to avoid data loss when changing storage config (Ingester restart).
Example of storage config change: Blue/Green setup with active/idle storage.
**Test platform**
=> feat(loki-microservices): flush ingester chunks on shutdown

README.adoc, aks/README.adoc, charts/loki-microservice/templates/event_handler.yaml, charts/loki-stack/templates/event_handler.yaml, eks/README.adoc, kind/README.adoc, locals.tf, variables.tf
Kubernetes events are useful during workload debugging but they expire after 60 minutes. This PR uses [Grafana Agent integration eventhandler](https://grafana.com/docs/agent/latest/configuration/integrations/integrations-next/eventhandler-config/#eventhandler_config) to ship events to Loki for persistence.
=> feat: ship k8s events to Loki

aks/README.adoc, aks/extra-variables.tf, aks/locals.tf, aks/main.tf, locals.tf
:warning: **Breaking change**
**Summary**
User can now choose between key-based and identity-based access to object storage.
The variable `logs_storage` is refactored as follow:
```hcl
logs_storage = {
container       = azurerm_storage_container.logs.name
storage_account = azurerm_storage_account.logs.name
managed_identity_node_rg_name = module.cluster.node_resource_group # Unset when using account key.
managed_identity_oidc_issuer_url = module.cluster.oidc_issuer_url # Unset when using account key.
storage_account_key = azurerm_storage_account.logs.primary_access_key # Unset when using a managed identity
}
```
**Imporant:** when using identity-based access, [azure-workload-identity](https://github.com/camptocamp/devops-stack-module-azure-workload-identity) must be declared as module …
=> feat(azure)!: use managed identity to access object storage

README.adoc, aks/README.adoc, eks/README.adoc, kind/README.adoc, locals.tf
Prometheus datasource is default and when Loki datasource is also set as default, it doesn't appear in Grafana. This PR fixes this issue for `loki-stack` deployments. Grafana restart is needed so the sidecar picks the new datasource.
=> fix(loki-stack): set Loki datasource isDefault to false

README.adoc, charts/loki-microservice/templates/event_handler.yaml, locals.tf
Added a fixed Grafana agent tag in order to avoid disruption. Reminder: Grafana agent ships K8s events to Loki
=> fix: grafana agent static tag

README.adoc, aks/README.adoc, charts/loki-stack/templates/event_handler.yaml, eks/README.adoc, kind/README.adoc
Following #52, this PR set a static tag for the monolithic version of loki.
=> fix(loki-stack): set static Grafana agent tag

README.adoc, aks/locals.tf
This PR fixes the error introduced by release 2.0.0 that breaks Loki setup with storage account key. The cause of the error is setting `use_federated_token` storage config parameter when using storage account key while it isn't supported for versions prior to 2.8.
The parameter is now only set when using a managed identity.
=> fix(azure): storage account key support

README.adoc, aks/README.adoc, eks/README.adoc, kind/README.adoc, locals.tf, variables.tf
As the current distributed Loki deploys a single replica of the ingester component, this can lead to log write interruptions and potential data loss during rollouts and restarts. So I configured the ingester to be deployed with replication factor of 3 and removed PodAffinity rules for the ingester to have replicas to any number of nodes (a nice feature to add later will be soft node affinity rules to make sure the ingester replicas are evenly deployed on multiples nodes).
=> feat: configure ingester replication factor

README.adoc, aks/README.adoc, aks/main.tf, eks/README.adoc, eks/main.tf, kind/README.adoc, kind/main.tf, locals.tf, variables.tf
Creation of a module variable that enables the retention of the Loki compactor because in the current configuration it is disabled.
:warning: **ATTENTION** :warning:
Platforms that use this module and do not apply retention - or have a longer retention window - need to update the retention input to avoid data loss.
=> feat: add var that enables compactor retention

.github/workflows/terraform-docs.yaml, README.adoc, aks/README.adoc, aks/outputs.tf, eks/README.adoc, eks/outputs.tf, kind/README.adoc, kind/extra-variables.tf, kind/locals.tf, kind/outputs.tf, outputs.tf, sks/README.adoc, sks/extra-variables.tf, sks/locals.tf, sks/main.tf, sks/outputs.tf, sks/terraform.tf, sks/variables.tf
This PR implements the SKS variant. It adds the necessary settings to use the S3 buckets on Exoscale and a nodeToleration to the Promtail, which is needed to deploy it on the router nodes that are tainted.
I also took the time to add a few descriptions to some outputs.
:warning: **Do a _Rebase and merge_.**
=> feat/fix: add SKS variant and standardize bucket configuration on other variants

.github/workflows/chart-upgrade.yaml, README.adoc
This PR is for testing if the auto upgrade of helm charts works correctly.
=> ci: add chart dependency upgrade workflow

README.adoc, aks/README.adoc, eks/README.adoc, kind/README.adoc, main.tf, sks/README.adoc, terraform.tf
Adapt the module to be compatible with ArgoCD versions >= 5.x (in counterpart, it now incompatible with previous versions of the provider). 
This change to the provider is needed to work with ArgoCD 2.7.x
=> feat!: add support to oboukili/argocd v5

README.adoc, locals.tf, sks/locals.tf
Adding taints to your nodes would mean having to add tolerations to Promtail, since this application is required to be deployed on all nodes to receive the logs and send them to Loki.
Before, we only added a specific toleration on the SKS variant to allow Promtail to be deployed on the router nodes, but I've since considered it better to have a more generic toleration, similar to the one from Prometheus Node Exporter DaemonSet. I did not find it necessary to variabilize these tolerations any further.
=> fix: use more generic tolerations for promtail

.github/workflows/chart-update.yaml, README.adoc, aks/README.adoc, eks/README.adoc, kind/README.adoc, main.tf, sks/README.adoc
This PR:
- re-adds the support to deactivate the auto-sync, which was broken by the use of dynamic Terraform blocks on the PR #59. This is not a breaking change, because users can still use the old way of passing an empty map to the `app_autosync` variable in order do deactivate the auto-sync.
- corrects a small typo on the auto-updater workflow.
:warning: **Do a _Rebase and merge_**
=> fix/ci: fix autosync deactivation and correct chart auto-updater workflow

README.adoc, aks/README.adoc, aks/main.tf, eks/README.adoc, eks/main.tf, kind/README.adoc, kind/main.tf, main.tf, sks/README.adoc, sks/main.tf, variables.tf
This PR:
- Adds the required variables and configuration to allow the module to be deployed on a different cluster than Argo CD.
- Adds the possibility of placing the application inside a specified Argo CD project in order to avoid having a single project for each application throughout multiple clusters.
- Adds labels and a variable to add more labels to the Argo CD application to make it easier to sort applications on the web interface of Argo CD.
- Removes old variable from the example in the README.adoc of SKS.
**All these changes are made in preparation for having a centralized Argo CD that controls applications throughout multiple clusters.**
:warning: **Do a _Rebase and merge_.**
=> feat: add variables to set AppProject, labels and destination cluster

README.adoc, aks/README.adoc, aks/extra-variables.tf, aks/locals.tf, aks/main.tf, eks/README.adoc, eks/main.tf, kind/README.adoc, kind/main.tf, locals.tf, main.tf, sks/README.adoc, sks/main.tf, variables.tf
The main changes of this PR are the following:
- **fix!: hardcode the release name to remove the destination cluster**
I found out that Argo CD passes the name of the application as a value to set the Helm chart. This means that all the templating that used `{ $.Release.Name }` would resolve to the name given to Argo CD application.
In a multicluster deployment, using a single Argo CD, the names of the applications must be different. We solved that by appending the cluster name to the default application name when deploying on different clusters than `in-cluster`. However, this resulted in multiple problems for deployments that depended on the name of the application being static, so this solves that.
This is a breaking change because sometimes this requires an application to be deleted …
=> fix!: remove the namespace variable, hardcode the Helm release name and other AKS changes 

README.adoc, aks/README.adoc, aks/main.tf, eks/README.adoc, kind/README.adoc, sks/README.adoc
Terraform is capable of deducting the Storage Account name and Resource Group name right away although the resources have yet been created. This means that the `data` resources on the `main.tf` try to reach resources which do not yet exist and this breaks the first deployment. I've added a `null_resource` to avoid this breakage.
=> fix(aks): add dependencies to fix reading of storage account

README.adoc, aks/README.adoc, aks/main.tf, eks/README.adoc, eks/main.tf, kind/README.adoc, kind/main.tf, locals.tf, sks/README.adoc, sks/main.tf, variables.tf
This PR adds a variable to set resources' limits and requests on the module components.
Having default values is good practice to prevent that our components could eventually starve other workloads on the cluster. However, these should probably be adapted in production clusters and are only a safeguard in case someone forgets to set them.
It also enables the embedded memcached for caching the index writes. This is something we have planned to do for a while, although I could not test its impact in the performance of Loki, because I do not have the log mass to test it.
:warning: **Do a _Rebase and merge_**
=> feat: add variable to set resources and enable caching for index writes

README.adoc, aks/README.adoc, aks/extra-variables.tf, eks/README.adoc, eks/extra-variables.tf, eks/locals.tf, eks/main.tf, kind/README.adoc, sks/README.adoc
This commit solves ISDEVOPS-279 and ISDEVOPS-283 for the EKS variant. That is, it adds support for creating the IAM role automatically inside the modules while also giving the chance to provide a custom one managed by the user.
:warning: **Do a _Rebase and merge_**
=> feat(eks)!: add option to create IAM role for the metrics storage

README.adoc, aks/README.adoc, aks/locals.tf, eks/README.adoc, eks/locals.tf, kind/README.adoc, kind/locals.tf, sks/README.adoc, sks/extra-variables.tf, sks/locals.tf
When creating an SKS cluster, Exoscale used to provision a cluster domain value of `<CLUSTER_ID>.cluster.local`. This is the legacy value for SKS cluster domain.
They recently transitioned to provisioning SKS cluster with the default cluster domain value of `cluster.local`.
Consequently, we need to remove the adaptations on our modules that were there to support this bizarre, and now legacy, behavior.
I also fixed a problem we had in the SKS, EKS and KinD configurations that was preventing `loki-compactor` from being correctly deployed from the v8.2.0 version of the module -> see [this commit message](https://github.com/camptocamp/devops-stack-module-loki-stack/pull/119/commits/acd71bad759dc7bb47209ef70934780055c7bb3a) for further explanations.
:warning: **Do a _Rebase and merge_**
=> feat!: remove the cluster_id variable || fix: remove the working_directory attribute in the compactor config 

README.adoc
This is just a cleanup that was forgotten when we depreciated the charts for `filebeat` and `loki-stack`.
=> docs: remove old charts from the README.adoc

README.adoc, aks/README.adoc, eks/README.adoc, kind/README.adoc, sks/README.adoc, terraform.tf
About two months ago, the Argo CD provider we use was moved under the umbrella of `argoproj-labs`. The move is now completed and the provider will no longer be available under `oboukili/argocd` but instead `argoproj-labs/argocd` . Version 6.2.0 of the provider is available under both, but they released v7.0.0 last week to finalize the migration.
Note the following:
- the v7 does not contain any changes to the API and serves only to mark the end of the move;
- the GPG key used to sign the provider is no longer the personal one from oboukili but instead the one from the argoproj-labs;
- the migration guide is [here](https://github.com/argoproj-labs/terraform-provider-argocd?tab=readme-ov-file#migrate-provider-source-oboukili---argoproj-labs);
- the release notes are …
=> feat!: point the Argo CD provider to the new repository
